# Generated by Django 3.1.2 on 2020-10-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=255)),
                ('runtime_seconds', models.IntegerField(blank=True, null=True)),
                ('plot', models.TextField(blank=True)),
                ('imdbID', models.CharField(blank=True, max_length=255)),
                ('dvd', models.CharField(blank=True, max_length=255)),
                ('box_office', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FilmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RatingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmWriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.CharField(max_length=255)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='actors', to='api.Person'),
        ),
        migrations.AddField(
            model_name='film',
            name='awards',
            field=models.ManyToManyField(blank=True, to='api.Award'),
        ),
        migrations.AddField(
            model_name='film',
            name='countries',
            field=models.ManyToManyField(blank=True, to='api.Country'),
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(blank=True, to='api.Person'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.filmtype'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(blank=True, to='api.Genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='languages',
            field=models.ManyToManyField(blank=True, to='api.Language'),
        ),
        migrations.AddField(
            model_name='film',
            name='posters',
            field=models.ManyToManyField(blank=True, to='api.Poster'),
        ),
        migrations.AddField(
            model_name='film',
            name='production',
            field=models.ManyToManyField(blank=True, to='api.LegalPerson'),
        ),
        migrations.AddField(
            model_name='film',
            name='website',
            field=models.ManyToManyField(blank=True, to='api.Website'),
        ),
        migrations.AddField(
            model_name='film',
            name='writers',
            field=models.ManyToManyField(related_name='writers', through='api.FilmWriter', to='api.Person'),
        ),
    ]
